services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: appandam
      POSTGRES_PASSWORD: appandam
      POSTGRES_DB: appandam
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U appandam -d appandam']
      interval: 2s
      timeout: 3s
      retries: 20

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  pgdata:
