/** Every user-facing string lives here (NFR-015). */
export const vi = {
  appName: 'Thực đơn ăn dặm',
  common: {
    retry: 'Thử lại',
    back: 'Quay lại',
    close: 'Đóng',
    loading: 'Đang tải…',
    comingSoon: 'Tính năng đang được xây dựng.',
  },
  nav: {
    label: 'Điều hướng chính',
    today: 'Hôm nay',
    week: 'Tuần',
    dishes: 'Món ăn',
    journal: 'Nhật ký',
    profile: 'Hồ sơ bé',
  },
  health: {
    checking: 'Đang kiểm tra máy chủ…',
    ok: 'Máy chủ hoạt động bình thường',
    down: 'Máy chủ đang gặp sự cố. Vui lòng thử lại sau ít phút.',
    offline: 'Không kết nối được máy chủ. Kiểm tra kết nối mạng của bạn.',
  },
  auth: {
    email: 'Email',
    password: 'Mật khẩu',
    newPassword: 'Mật khẩu mới',
    showPassword: 'Hiện mật khẩu',
    hidePassword: 'Ẩn mật khẩu',
    passwordHint: 'Ít nhất 8 ký tự. Có thể dùng câu dài dễ nhớ.',
    loginTitle: 'Đăng nhập',
    loginSubmit: 'Đăng nhập',
    loginIntro: 'Lên thực đơn ăn dặm an toàn theo độ tuổi của bé.',
    forgotLink: 'Quên mật khẩu?',
    noAccount: 'Chưa có tài khoản?',
    registerLink: 'Tạo tài khoản',
    registerTitle: 'Tạo tài khoản',
    registerSubmit: 'Tạo tài khoản',
    hasAccount: 'Đã có tài khoản?',
    consentLegend: 'Dữ liệu của bé',
    consentSummary:
      'Để lập thực đơn, ứng dụng lưu hồ sơ của bé, bữa ăn và các phản ứng bạn ghi lại. Đây là dữ liệu sức khỏe — dữ liệu cá nhân nhạy cảm — chỉ dùng để lập thực đơn cho bé, không chia sẻ cho bên thứ ba. Bạn có thể xóa toàn bộ dữ liệu bất cứ lúc nào.',
    consentPolicyLink: 'Đọc chính sách đầy đủ',
    consentCheckbox: 'Tôi đồng ý cho ứng dụng xử lý dữ liệu của bé như trên',
    consentRequired: 'Cần đồng ý với chính sách xử lý dữ liệu để tiếp tục',
    consentOutdated: 'Chính sách vừa được cập nhật. Vui lòng tải lại trang và đồng ý lại.',
    forgotTitle: 'Quên mật khẩu',
    forgotIntro: 'Nhập email đã đăng ký, chúng tôi sẽ gửi liên kết đặt lại mật khẩu.',
    forgotSubmit: 'Gửi liên kết',
    forgotSent:
      'Nếu email này đã đăng ký, chúng tôi vừa gửi liên kết đặt lại mật khẩu. Liên kết có hiệu lực trong 30 phút.',
    resetTitle: 'Đặt mật khẩu mới',
    resetSubmit: 'Đặt mật khẩu mới',
    resetDone: 'Đã đổi mật khẩu. Mọi thiết bị khác đã được đăng xuất.',
    resetInvalid: 'Liên kết không hợp lệ hoặc đã hết hạn.',
    resetRequestAgain: 'Gửi liên kết mới',
    backToLogin: 'Đăng nhập',
    signedInAs: 'Đang đăng nhập với',
    logout: 'Đăng xuất',
  },
  privacy: {
    title: 'Chính sách xử lý dữ liệu',
    sections: [
      {
        heading: 'Dữ liệu được thu thập',
        body: 'Email và mật khẩu (đã mã hóa); hồ sơ bé: tên, ngày sinh, thực phẩm cần tránh; bữa ăn, lượng ăn, mức thích, dấu hiệu bất thường và tình trạng sức khỏe bạn ghi lại.',
      },
      {
        heading: 'Mục đích',
        body: 'Chỉ để lập thực đơn phù hợp và an toàn cho bé, và để bạn xem lại nhật ký khi đi khám. Ứng dụng không chẩn đoán bệnh.',
      },
      {
        heading: 'Quyền của bạn',
        body: 'Bạn có thể xem, sửa, và xóa dữ liệu của từng bé hoặc xóa toàn bộ tài khoản. Tài khoản bị xóa sẽ không truy cập được ngay và dữ liệu bị xóa vĩnh viễn trong vòng 30 ngày.',
      },
      {
        heading: 'Bảo mật',
        body: 'Dữ liệu được truyền qua kết nối mã hóa và chỉ tài khoản của bạn truy cập được.',
      },
    ],
  },
  notFound: {
    title: 'Không tìm thấy trang',
    body: 'Trang bạn mở không tồn tại hoặc đã được chuyển đi.',
    home: 'Về trang Hôm nay',
  },
  onboarding: {
    title: 'Tạo hồ sơ bé',
    next: 'Tiếp tục',
    nameTitle: 'Bé nhà mình tên gì?',
    nameLabel: 'Tên hoặc tên gọi ở nhà của bé',
    nameRequired: 'Nhập tên của bé',
    nameTooLong: 'Tên bé tối đa 30 ký tự',
    birthTitle: (name: string) => `${name} sinh ngày nào?`,
    birthLabel: 'Ngày sinh',
    birthRequired: 'Chọn ngày sinh của bé',
    birthFuture: 'Ngày sinh không thể ở tương lai',
    premature: 'Bé sinh non',
    prematureHint: 'Dùng tuổi hiệu chỉnh theo tư vấn bác sĩ',
    weeksLabel: 'Sinh sớm bao nhiêu tuần?',
    weeksRange: 'Nhập số tuần từ 1 đến 16',
    weeksEarly: (weeks: number) => `Sinh sớm ${weeks} tuần`,
    avoidTitle: (name: string) => `Bé ${name} cần tránh thực phẩm nào?`,
    avoidIntro:
      'Món chứa những thực phẩm này sẽ không bao giờ xuất hiện trong thực đơn — kể cả khi kho món ít.',
    reactionLegend: 'Bé đã từng có phản ứng sau khi ăn?',
    reactions: { never: 'Chưa từng', yes: 'Có — tôi sẽ ghi lại chi tiết', unsure: 'Không chắc' },
    reactionTitle: 'Ghi lại phản ứng trước đây',
    reactionNoteLabel: 'Bé đã phản ứng thế nào, với thực phẩm gì?',
    reactionNotePlaceholder: 'Ví dụ: nổi mẩn ở má khoảng 1 giờ sau khi ăn trứng',
    doctorNote:
      'Nếu bé có vấn đề sức khỏe đặc biệt, hãy trao đổi với bác sĩ trước khi dùng thực đơn gợi ý.',
    summaryTitle: 'Kiểm tra lại thông tin',
    avoidSummary: 'Thực phẩm cần tránh',
    none: 'Không có',
    create: 'Tạo hồ sơ',
    fix: 'Sửa thông tin',
  },
  ageSettings: {
    header: 'Cài đặt độ tuổi',
    title: 'Độ tuổi & giai đoạn ăn dặm',
    intro: 'Thực đơn chọn kết cấu, số bữa và khẩu phần theo giai đoạn này.',
    birthDate: 'Ngày sinh',
    planningAge: 'Tuổi dùng để lên thực đơn',
    updating: 'Đang cập nhật…',
    stages: 'Giai đoạn',
    backToAge: 'Về theo tuổi',
    byAge: 'Theo tuổi',
    unlockAt: (months: number) => `Mở khi bé đủ ${months} tháng`,
    hints: [
      'Nghiền mịn, sệt dần',
      'Nghiền lợn cợn, cháo đặc',
      'Cắt nhỏ, mềm, bé tự cầm',
      'Ăn cùng gia đình, ít gia vị',
    ],
    overrideWarning:
      'Bạn đang giữ giai đoạn sớm hơn tuổi của bé — phù hợp khi bé chưa quen kết cấu mới. Không thể chọn giai đoạn cao hơn tuổi.',
    applied: 'Thực đơn sẽ áp dụng',
    texture: 'Kết cấu',
    portion: 'Khẩu phần mỗi bữa',
    mainMeals: 'Bữa chính / ngày',
    snacks: 'Bữa phụ',
    noSnack: 'Chưa cần',
    tooYoung: 'Dưới 6 tháng, ứng dụng chưa lập thực đơn ăn dặm.',
    tooOld: 'Ứng dụng hỗ trợ bé đến 24 tháng tuổi.',
    save: 'Lưu và cập nhật thực đơn',
    who: 'Tham khảo theo hướng dẫn WHO về ăn bổ sung (6–23 tháng). Dưới 6 tháng, ứng dụng không lập thực đơn ăn dặm.',
  },
  profile: {
    notPlannable: 'Chưa đến tuổi ăn dặm',
    avoidTitle: 'Thực phẩm cần tránh',
    avoidEmpty: 'Chưa có thực phẩm cần tránh',
    editAvoid: 'Sửa thực phẩm cần tránh',
    save: 'Lưu',
    cancel: 'Hủy',
    settings: 'Cài đặt',
    ageLink: 'Độ tuổi & giai đoạn',
    accountLink: 'Tài khoản',
    deleteChild: 'Xóa dữ liệu của bé',
    deleteWarning: (name: string) =>
      `Toàn bộ hồ sơ, thực đơn và nhật ký của ${name} sẽ bị xóa vĩnh viễn và không thể khôi phục.`,
    deleteForever: 'Xóa vĩnh viễn',
    readOnly: 'Bạn là người chăm: chỉ chủ hồ sơ sửa được phần này.',
  },
  account: {
    title: 'Tài khoản',
    deleteTitle: 'Xóa tài khoản',
    deleteExplain:
      'Tài khoản và dữ liệu của mọi bé sẽ không truy cập được ngay, và bị xóa vĩnh viễn trong vòng 30 ngày.',
    passwordLabel: 'Nhập mật khẩu để xác nhận',
    passwordRequired: 'Nhập mật khẩu hiện tại để xác nhận',
    delete: 'Xóa tài khoản',
    nameTitle: 'Tên hiển thị',
    nameLabel: 'Tên người nhà thấy',
    nameHint: 'Ví dụ: Mẹ Na, Bà nội. Để trống sẽ dùng phần trước @ của email.',
    nameSave: 'Lưu tên',
    nameSaved: 'Đã lưu tên hiển thị.',
    transferFirst: 'Hãy chuyển quyền chủ hoặc xóa các hồ sơ bé sau trước khi xóa tài khoản:',
  },
  child: {
    newborn: 'Mới sinh',
    corrected: 'hiệu chỉnh',
  },
  allergens: {
    egg: 'Trứng',
    cow_milk: 'Sữa bò',
    peanut: 'Đậu phộng',
    shellfish: 'Tôm, cua',
    fish: 'Cá',
    wheat: 'Lúa mì',
    soy: 'Đậu nành',
    sesame: 'Mè',
    tree_nut: 'Hạt cây',
  },
  avoid: {
    allergensLegend: 'Chất gây dị ứng thường gặp',
    otherLabel: 'Thực phẩm khác bé không ăn hoặc không thích',
    otherPlaceholder: 'Tìm nguyên liệu, ví dụ: cà rốt',
    noResult: 'Không tìm thấy nguyên liệu phù hợp',
    alreadyAdded: (name: string) => `${name} đã có trong danh sách`,
    add: 'Thêm',
    remove: 'Bỏ',
    switchReason: 'Đổi lý do cho',
    reasons: { dislike: 'không thích', not_eat: 'không ăn' },
  },
  slots: {
    breakfast: 'Sáng',
    morning_snack: 'Phụ sáng',
    lunch: 'Trưa',
    afternoon_snack: 'Xế',
    dinner: 'Tối',
    extra_snack: 'Phụ tối',
  },
  foodGroups: {
    carb: 'Tinh bột',
    protein: 'Đạm',
    fat: 'Chất béo',
    veg: 'Rau củ',
    fruit: 'Trái cây',
    seasoning: 'Gia vị',
  },
  proteins: {
    fish: 'Cá',
    chicken: 'Gà',
    beef: 'Bò',
    pork: 'Heo',
    legume: 'Đậu',
    egg: 'Trứng',
  },
  groupsMet: (count: number) => `Đạt ${count}/4 nhóm`,
  minutes: (count: number) => `${count} phút`,
  today: {
    childName: (name: string) => `Bé ${name}`,
    stage: (id: number) => `Giai đoạn ${id}`,
    texture: (label: string) => `Kết cấu: ${label}`,
    health: (status: string) => `Sức khỏe: ${status}`,
    healthOverdue: (end: string) =>
      `Đã qua ngày dự kiến khỏi (${end}). Bé đã khỏe hơn chưa? Cập nhật để thực đơn theo kịp.`,
    updateHealth: 'Cập nhật sức khỏe',
    avoid: (names: string) => `Tránh: ${names}`,
    nextMeal: 'Bữa tiếp theo',
    nextMealAt: (slot: string, time: string) => `Bữa tiếp theo · ${slot} ${time}`,
    due: 'đã tới giờ',
    firstTry: (names: string) => `Lần đầu thử: ${names}.`,
    firstTryAdvice: 'Cho lượng nhỏ và theo dõi bé trong vài giờ sau bữa.',
    prepared: 'Đã chuẩn bị xong',
    preparedDone: 'Đã chuẩn bị xong — cho bé ăn rồi ghi lại nhé.',
    swap: 'Đổi món',
    ate: 'Bé đã ăn',
    reaction: 'Phản ứng',
    listTitle: 'Hôm nay',
    listLabel: 'Thực đơn hôm nay',
    status: {
      next: 'Tiếp theo',
      prepared: 'Đã chuẩn bị',
      eaten: 'Đã ăn',
      refused: 'Bé không ăn',
      skipped: 'Đã bỏ qua',
    },
    snack: 'Bữa phụ',
    unfilled: 'Chưa có món phù hợp',
    unfilledAlert:
      'Chưa tìm được món an toàn cho một số bữa. Thực phẩm bé cần tránh luôn được loại trừ, kể cả khi kho món ít.',
    reviewAvoid: 'Xem thực phẩm cần tránh',
    doneTitle: 'Hôm nay đã xong',
    doneBody: 'Các bữa hôm nay đã được ghi lại. Thực đơn ngày mai sẽ có ở đây từ sáng mai.',
    loading: 'Đang lập thực đơn…',
    tooYoung: 'Dưới 6 tháng, ứng dụng chưa lập thực đơn ăn dặm.',
    tooOld: 'Ứng dụng hỗ trợ bé đến 24 tháng tuổi.',
    checkAge: 'Kiểm tra độ tuổi',
    disclaimer: 'Thực đơn là gợi ý tham khảo, không thay thế tư vấn của nhân viên y tế.',
  },
  healthStatus: {
    normal: 'Bình thường',
    sick: 'Đang ốm',
    recovering: 'Đang hồi phục',
  },
  healthPage: {
    title: (name: string) => `Hôm nay bé ${name} thế nào?`,
    intro: 'Thực đơn sẽ điều chỉnh số bữa và kết cấu món theo trạng thái bạn chọn.',
    statusLegend: 'Trạng thái sức khỏe',
    statusHints: {
      normal: 'Thực đơn đầy đủ theo độ tuổi',
      sick: 'Món mềm, lỏng, dễ ăn; chia nhỏ bữa',
      recovering: 'Tăng dần lượng và kết cấu về bình thường',
    },
    symptomsLegend: 'Bạn thấy bé có biểu hiện gì?',
    symptoms: {
      fever: 'Sốt',
      poor_appetite: 'Biếng ăn',
      cough: 'Ho, sổ mũi',
      diarrhea: 'Tiêu chảy',
      vomit: 'Nôn',
      teething: 'Mọc răng',
    },
    start: 'Bắt đầu',
    expectedEnd: 'Dự kiến kết thúc',
    expectedEndHint: 'Để trống nếu chưa rõ',
    endBeforeStart: 'Ngày kết thúc phải từ ngày bắt đầu trở đi',
    changesTitle: 'Thực đơn sẽ thay đổi',
    changes: {
      splitMeals: 'Chia nhỏ thành nhiều bữa, lượng mỗi bữa ít hơn',
      smallerPortions: (percent: number) => `Lượng mỗi bữa khoảng ${percent}% so với bình thường`,
      softer: 'Ưu tiên món mềm, lỏng hơn một mức kết cấu',
      stageTexture: 'Kết cấu theo giai đoạn của bé',
      pauseNew: 'Tạm ngưng thử nguyên liệu mới',
      fullMenu: 'Thực đơn đầy đủ theo độ tuổi',
      newFoodsOk: 'Tiếp tục cho bé làm quen thực phẩm mới',
    },
    updating: 'Đang cập nhật…',
    disclaimer:
      'Ứng dụng không chẩn đoán bệnh. Nếu bé sốt cao, bỏ bú, lừ đừ hoặc có dấu hiệu mất nước, hãy đưa bé đi khám.',
    urgentLink: 'Xem dấu hiệu nguy hiểm',
    submit: 'Cập nhật thực đơn',
  },
  week: {
    eyebrow: (name: string, range: string) => `Bé ${name} · Tuần ${range}`,
    title: 'Thực đơn tuần',
    previous: 'Tuần trước',
    next: 'Tuần sau',
    distinct: 'Món khác nhau',
    distinctValue: (total: number) => `/ ${total} bữa`,
    fullGroups: 'Ngày đạt mục tiêu 4 nhóm',
    fullGroupsValue: (days: number) => `/ ${days} ngày`,
    rotation: 'Xoay vòng nguồn đạm',
    rotationUnit: 'số bữa',
    avoided: 'Đang tránh theo hồ sơ',
    daysLabel: 'Các ngày trong tuần',
    weekdays: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
    today: 'Hôm nay',
    planned: 'kế hoạch',
    groups: (n: number) => `${n}/4`,
    groupsLabel: (n: number) => `Đạt ${n}/4 nhóm chất`,
    newFood: 'mới',
    noPlan: 'Chưa có thực đơn',
    planNext: 'Lên thực đơn tuần sau',
    replaceTitle: 'Tuần sau đã có thực đơn.',
    replaceBody: 'Thay các bữa chưa nấu, chưa ghi nhận bằng thực đơn mới?',
    replace: 'Thay thực đơn mới',
    keep: 'Giữ thực đơn hiện có',
    disclaimer: 'Các chỉ số giúp bạn cân nhắc, không phải điểm đánh giá việc chăm bé.',
    loading: 'Đang tải thực đơn tuần…',
  },
  dayDetail: {
    listLabel: 'Thực đơn trong ngày',
    title: 'Các bữa',
    empty: 'Ngày này chưa có thực đơn.',
  },
  recipe: {
    photo: 'Ảnh món ăn',
    reviewed: 'Đã duyệt nội dung',
    notReviewed: 'Chưa được chuyên gia duyệt',
    version: (v: number) => `Công thức v${v}`,
    custom: 'Món của bạn',
    customNote: 'Món do bạn tạo, chưa qua chuyên gia dinh dưỡng duyệt.',
    anyQty: 'Tùy ý',
    edit: 'Sửa món',
    prep: 'Sơ chế',
    cook: 'Nấu',
    texture: 'Kết cấu',
    tool: 'Dụng cụ',
    byAge: 'Theo độ tuổi',
    byAgeLabel: 'Hướng dẫn theo độ tuổi',
    facts: 'Thông tin món',
    portion: 'Khẩu phần tham khảo',
    ingredients: 'Nguyên liệu · 1 phần',
    ingredientsLabel: 'Nguyên liệu',
    firstTry: '· lần đầu',
    safety: 'Lưu ý an toàn',
    allergens: 'Chứa chất gây dị ứng thường gặp:',
    steps: 'Cách làm',
    swap: 'Đổi món',
    startCooking: 'Bắt đầu nấu',
    excluded: 'Món này hiện không phù hợp với bé',
    exclusions: {
      allergen: 'Món có chất gây dị ứng bé cần tránh.',
      avoid: 'Món có thực phẩm bé không ăn hoặc không thích.',
      paused: 'Món có thực phẩm đang tạm dừng sau một phản ứng.',
      age: 'Món chưa phù hợp với độ tuổi của bé.',
      refused: 'Bé đã từ chối món này gần đây.',
      sick_new: 'Món có thực phẩm mới — chưa nên thử khi bé đang mệt.',
    },
  },
  swap: {
    eyebrow: (slot: string, time: string) => `Bữa ${slot} · ${time}`,
    title: 'Đổi món khác',
    replacing: (name: string) => `Đang thay: ${name}`,
    reasonLegend: 'Vì sao muốn đổi?',
    reasons: {
      missing_ingredient: 'Thiếu nguyên liệu',
      disliked: 'Bé không thích',
      faster: 'Cần nấu nhanh hơn',
      other: 'Lý do khác',
    },
    suggestions: 'Gợi ý thay thế',
    best: 'Phù hợp nhất',
    chooseBest: 'Chọn món này',
    choose: 'Chọn',
    chooseLabel: (name: string) => `Chọn ${name}`,
    updating: 'Đang cập nhật…',
    fasterBy: (minutes: number) => `Nhanh hơn ${minutes} phút`,
    codes: {
      NOT_USED_7D: 'Chưa dùng trong 7 ngày qua',
      LIKED: 'Bé từng ăn hết hoặc rất thích món này',
      FOUR_GROUPS: 'Đủ 4 nhóm chất',
      LEAST_USED_PROTEIN: 'Nguồn đạm bé ít ăn trong tuần',
      NEW_INGREDIENT: 'Có thực phẩm mới để bé làm quen',
    },
    differentProtein: (protein: string, others: string) =>
      `Đạm ${protein} — khác nguồn đạm ${others}`,
    differentProteinAlone: (protein: string) => `Đạm ${protein} — chưa có trong các bữa khác`,
    proteinOther: (slot: string, protein: string) => `bữa ${slot} (${protein})`,
    repeatPast: (days: number) => `Đã dùng ${days} ngày trước`,
    repeatAhead: (days: number) => `Đã có trong thực đơn ${days} ngày tới`,
    relaxed: 'hệ thống nới cửa sổ chống lặp từ 7 xuống 3 ngày vì kho món còn ít.',
    excluded: (count: number, parts: string) => `Đã loại ${count} món: ${parts}.`,
    neverRelaxed: 'Bộ lọc an toàn không bao giờ được nới.',
    noFaster: 'Không có món nào nhanh hơn món hiện tại.',
    none: 'Chưa có món phù hợp để thay.',
    openLibrary: 'Mở thư viện món',
    home: 'Về trang Hôm nay',
  },
  exclusionParts: {
    allergen: (n: string, names: string) => `${n} chứa ${names} (cần tránh)`,
    avoid: (n: string) => `${n} có thực phẩm bé không ăn`,
    paused: (n: string) => `${n} có thực phẩm đang tạm dừng`,
    age: (n: string) => `${n} chưa hợp độ tuổi`,
    refused: (n: string) => `${n} bé từng từ chối`,
    sick_new: (n: string) => `${n} có thực phẩm mới khi bé đang mệt`,
    allergensFallback: 'chất gây dị ứng',
  },
  library: {
    title: 'Món ăn',
    filtered: (name: string, stage: number) => `Đã lọc cho bé ${name} · Giai đoạn ${stage}`,
    avoiding: (names: string) => `tránh ${names}`,
    searchLabel: 'Tìm món',
    searchPlaceholder: 'Tìm món hoặc nguyên liệu',
    chipsLabel: 'Lọc theo nhóm',
    chips: {
      all: 'Tất cả',
      chicken: 'Gà',
      fish: 'Cá',
      beef: 'Bò',
      pork: 'Heo',
      legume: 'Đậu',
      snack: 'Bữa phụ',
      custom: 'Món của bạn',
    },
    create: 'Tạo món',
    count: (n: number) => `${n} món phù hợp`,
    fresh: 'Chưa ăn 7 ngày',
    main: 'Món chính',
    snack: 'Bữa phụ',
    liked: 'Bé thích',
    firstTry: (names: string) => `Lần đầu: ${names}`,
    eatenToday: {
      breakfast: 'Ăn sáng nay',
      lunch: 'Ăn trưa nay',
      dinner: 'Ăn tối nay',
      other: 'Ăn hôm nay',
    },
    eatenYesterday: 'Ăn hôm qua',
    eatenDaysAgo: (n: number) => `Ăn ${n} ngày trước`,
    empty: 'Chưa có món phù hợp trong nhóm này.',
    emptyQuery: (q: string) => `Không tìm thấy món khớp “${q}”.`,
    dropFresh: 'Bỏ lọc “Chưa ăn 7 ngày”',
    hiddenTitle: (n: number) => `Đang ẩn ${n} món không phù hợp`,
    hiddenMatching: (n: number) => `${n} món khớp từ khóa đang bị ẩn`,
    hiddenLabel: 'Món đang ẩn',
    showHidden: 'Xem các món đang ẩn',
    hideHidden: 'Thu gọn',
    hiddenReasons: {
      allergen: 'có chất gây dị ứng cần tránh',
      avoid: 'có thực phẩm bé không ăn',
      paused: 'có thực phẩm đang tạm dừng',
      age: 'chưa hợp độ tuổi',
      refused: 'bé từng từ chối',
      sick_new: 'có thực phẩm mới khi bé đang mệt',
    },
  },
  log: {
    eyebrow: (slot: string, time: string) => `${slot} · ${time}`,
    title: 'Bé đã ăn thế nào?',
    time: 'Giờ ghi nhận',
    amountLegend: 'Lượng bé ăn',
    amounts: {
      none: 'Không ăn',
      few_spoons: 'Vài thìa',
      quarter: '1/4 phần',
      half: 'Nửa phần',
      almost_all: 'Gần hết',
      all: 'Hết',
    },
    likingLabel: 'Bé có thích món này?',
    likingLow: 'Từ chối',
    likingHigh: 'Rất thích',
    reactionLabel: 'Phản ứng sau ăn',
    reactionTitle: 'Có dấu hiệu bất thường?',
    firstTryIntro: 'Hôm nay bé lần đầu thử',
    reactionHint: 'Ghi lại nếu bạn thấy điều gì khác thường.',
    symptomsLabel: 'Dấu hiệu bất thường',
    symptoms: {
      rash: 'Nổi mẩn đỏ',
      vomit: 'Nôn trớ',
      diarrhea: 'Tiêu chảy',
      swelling: 'Sưng môi, mặt',
      breathing: 'Khó thở',
      fussy: 'Quấy khóc',
    },
    severityLegend: 'Mức độ bạn thấy',
    severities: { unknown: 'Chưa rõ', mild: 'Nhẹ', moderate: 'Vừa', severe: 'Nặng' },
    note: 'Ghi chú',
    notePlaceholder: 'Ví dụ: mẩn ở má, xuất hiện khoảng 1 giờ sau ăn',
    noteCount: (n: number) => `${n}/500`,
    willPauseBefore: 'Sau khi lưu,',
    willPauseAfter:
      'sẽ tạm không được gợi ý cho đến khi bạn xác nhận lại. Ứng dụng không kết luận nguyên nhân.',
    nothingToPause:
      'Ghi nhận được lưu vào nhật ký để bạn đưa bác sĩ xem. Ứng dụng không kết luận nguyên nhân.',
    danger: 'Khó thở, sưng môi mặt hoặc dấu hiệu nặng cần được xử lý ngay.',
    dangerLink: 'Xem dấu hiệu nguy hiểm',
    required: 'Chọn lượng bé ăn và mức thích để lưu.',
    save: 'Lưu ghi nhận',
    saving: 'Đang lưu…',
    urgent: 'Bé có dấu hiệu nguy hiểm',
    notSaved: 'Chưa lưu được. Thông tin bạn nhập vẫn được giữ — hãy thử lại.',
    savedTitle: 'Đã lưu ghi nhận',
    paused: (names: string) =>
      `${names} tạm không được gợi ý cho đến khi bạn xác nhận lại sau khi hỏi ý kiến bác sĩ.`,
    backHome: 'Về trang Hôm nay',
    loggedBy: (name: string, time: string) => `${name} đã ghi nhận lúc ${time}`,
    deletedUser: 'Người dùng đã xóa',
    liking: (n: number) => `Mức thích ${n}/5`,
  },
  urgent: {
    title: 'Gọi cấp cứu ngay nếu bé có một trong các dấu hiệu sau',
    signs: [
      'Khó thở, thở rít hoặc ho liên tục',
      'Sưng môi, lưỡi hoặc mặt',
      'Nôn nhiều lần liên tiếp',
      'Lừ đừ, khó đánh thức, tím tái',
    ],
    signsLabel: 'Dấu hiệu cần gọi cấp cứu',
    call: 'Gọi 115',
    contacted: 'Tôi đã liên hệ nhân viên y tế',
    contactedAt: (time: string) => `Đã ghi nhận liên hệ y tế lúc ${time}`,
    pausedTitle: 'Đã tạm dừng gợi ý liên quan',
    pausedText: (names: string) =>
      `${names} sẽ không xuất hiện trong thực đơn cho đến khi bạn xác nhận lại sau khi hỏi ý kiến bác sĩ.`,
    pausing: 'Đang tạm dừng gợi ý liên quan…',
    notRecorded: 'Chưa ghi nhận được. Bạn vẫn có thể gọi 115 ngay.',
    retry: 'Thử ghi nhận lại',
    disclaimer:
      'Ứng dụng không chẩn đoán và không kết luận nguyên nhân. Ghi nhận này được lưu lại để bạn đưa cho bác sĩ xem.',
  },
  paused: {
    title: 'Nguyên liệu tạm dừng',
    empty: 'Không có nguyên liệu nào đang tạm dừng.',
    reasons: { reaction: 'Sau phản ứng', urgent: 'Sau dấu hiệu nguy hiểm' },
    since: (date: string) => `từ ${date}`,
    resume: 'Bác sĩ đã cho phép dùng lại',
    resumeLabel: (name: string) => `Bác sĩ đã cho phép dùng lại ${name}`,
    confirm: (name: string) => `Dùng lại ${name}? Các món có ${name} sẽ được gợi ý trở lại.`,
    confirmYes: 'Xác nhận dùng lại',
    cancel: 'Hủy',
  },
  journal: {
    title: 'Nhật ký',
    empty: 'Chưa có ghi nhận nào. Sau mỗi bữa, bấm “Bé đã ăn” để ghi lại.',
    more: 'Xem thêm',
    urgent: 'Mở “Dấu hiệu nguy hiểm”',
    contacted: (time: string) => `Đã liên hệ y tế lúc ${time}`,
    liking: (n: number) => `thích ${n}/5`,
    paused: (names: string) => `Tạm dừng: ${names}`,
    by: (name: string) => `bởi ${name}`,
    today: 'Hôm nay',
    yesterday: 'Hôm qua',
  },
  members: {
    title: 'Người cùng chăm bé',
    roles: { owner: 'Chủ hồ sơ', caregiver: 'Người chăm' },
    me: 'Bạn',
    since: (date: string) => `tham gia ${date}`,
    invite: 'Mời người chăm',
    inviteHint:
      'Ba/mẹ, ông bà hoặc người giúp việc sẽ cùng xem thực đơn và ghi nhận bữa ăn cho bé.',
    linkReady: 'Gửi link này cho người nhà',
    linkWarning: 'Ai có link đều tham gia được trong 72 giờ — chỉ gửi qua tin nhắn riêng.',
    linkLabel: 'Link mời',
    share: 'Chia sẻ link',
    copy: 'Sao chép link',
    copied: 'Đã sao chép',
    shareText: (child: string) => `Cùng chăm bé ${child} trên Thực đơn ăn dặm`,
    pending: 'Lời mời đang chờ',
    expires: (date: string) => `hết hạn ${date}`,
    revoke: 'Thu hồi',
    revokeLabel: (date: string) => `Thu hồi lời mời hết hạn ${date}`,
    remove: 'Gỡ',
    removeLabel: (name: string) => `Gỡ ${name}`,
    removeConfirm: (name: string) => `Gỡ ${name}? Người này sẽ không xem được hồ sơ bé nữa.`,
    makeOwner: 'Chuyển quyền chủ',
    makeOwnerLabel: (name: string) => `Chuyển quyền chủ cho ${name}`,
    makeOwnerConfirm: (name: string) =>
      `Chuyển quyền chủ hồ sơ cho ${name}? Bạn sẽ thành người chăm và không sửa được hồ sơ bé nữa.`,
    leave: 'Rời hồ sơ bé',
    leaveConfirm: (child: string) =>
      `Rời hồ sơ của ${child}? Bạn sẽ không xem được thực đơn của bé nữa.`,
    confirm: 'Xác nhận',
    cancel: 'Hủy',
    caregiverNote: 'Chỉ chủ hồ sơ sửa được thông tin bé, thực phẩm cần tránh và người cùng chăm.',
  },
  invite: {
    title: 'Lời mời chăm bé',
    body: (inviter: string, child: string) => `${inviter} mời bạn cùng chăm bé ${child}.`,
    rights:
      'Bạn sẽ xem được thực đơn, công thức, nhật ký và tình trạng sức khỏe của bé; đổi món và ghi nhận bữa ăn.',
    health: 'Đây là dữ liệu sức khỏe của trẻ — chỉ tham gia nếu bạn thực sự cùng chăm bé.',
    expires: (date: string) => `Lời mời hết hạn ${date}.`,
    join: 'Tham gia',
    login: 'Đăng nhập để tham gia',
    register: 'Tạo tài khoản',
    errors: {
      INVITE_NOT_FOUND: 'Link mời không đúng. Hãy kiểm tra lại link người nhà gửi.',
      INVITE_EXPIRED: 'Link mời đã hết hạn. Hãy nhờ người nhà gửi link mới.',
      INVITE_REVOKED: 'Link mời đã bị thu hồi. Hãy nhờ người nhà gửi link mới.',
      INVITE_USED: 'Link mời đã được dùng. Mỗi link chỉ dùng được một lần.',
    },
    home: 'Về trang Hôm nay',
  },
  switcher: {
    open: (name: string) => `Đổi bé, đang xem bé ${name}`,
    title: 'Chọn bé',
    role: { owner: 'Chủ hồ sơ', caregiver: 'Người chăm' },
    close: 'Đóng',
  },
  customDish: {
    createTitle: 'Tạo món của bạn',
    editTitle: 'Sửa món',
    intro: 'Món chỉ dùng cho bé, vẫn được kiểm tra bộ lọc an toàn theo hồ sơ.',
    name: 'Tên món',
    namePlaceholder: 'Ví dụ: Cháo gà bí đỏ nhà làm',
    mealType: 'Loại bữa',
    mealTypes: { main: 'Bữa chính', snack: 'Bữa phụ' },
    ingredients: 'Nguyên liệu',
    ingredientsHint: 'Chọn từ danh mục, tối đa 15 nguyên liệu. Định lượng không bắt buộc.',
    search: 'Tìm nguyên liệu',
    searchPlaceholder: 'Ví dụ: thịt gà',
    noResult: 'Không tìm thấy nguyên liệu phù hợp',
    add: (name: string) => `Thêm ${name}`,
    added: 'Đã thêm',
    qty: (name: string) => `Định lượng ${name}`,
    unit: (name: string) => `Đơn vị ${name}`,
    qtyPlaceholder: 'Tùy ý',
    unitPlaceholder: 'g',
    remove: (name: string) => `Bỏ ${name}`,
    groups: 'Món đạt nhóm chất',
    noGroups: 'Thêm nguyên liệu để xem nhóm chất',
    prepMin: 'Sơ chế (phút)',
    cookMin: 'Nấu (phút)',
    steps: 'Các bước (không bắt buộc)',
    step: (n: number) => `Bước ${n}`,
    addStep: 'Thêm bước',
    removeStep: (n: number) => `Xóa bước ${n}`,
    save: 'Lưu món',
    saving: 'Đang lưu…',
    delete: 'Xóa món',
    deleteConfirm: (name: string) =>
      `Xóa “${name}”? Món sẽ không còn được gợi ý; các bữa đã ăn vẫn giữ tên món.`,
    deleteYes: 'Xóa món',
    cancel: 'Hủy',
    unsafe: 'Món có nguyên liệu không phù hợp với bé lúc này:',
    unsafeReasons: {
      allergen: 'chất gây dị ứng cần tránh',
      avoid: 'bé không ăn',
      paused: 'đang tạm dừng',
      age: 'chưa hợp độ tuổi',
    },
    fields: {
      name: 'Tên món cần từ 2 đến 60 ký tự.',
      ingredients: 'Chọn từ 1 đến 15 nguyên liệu.',
      prepMin: 'Thời gian sơ chế từ 0 đến 180 phút.',
      cookMin: 'Thời gian nấu từ 0 đến 240 phút, tổng ít nhất 1 phút.',
      steps: 'Tối đa 15 bước, mỗi bước tối đa 300 ký tự.',
      qty: 'Định lượng lớn hơn 0 và tối đa 9 999.',
      unit: 'Đơn vị tối đa 12 ký tự.',
    },
  },
  textures: {
    puree_smooth: 'Nghiền mịn',
    mashed: 'Nghiền',
    lumpy: 'Lợn cợn',
    minced_soft: 'Cắt nhỏ, mềm',
    family: 'Món gia đình',
  },
  errors: {
    GENERIC: 'Đã có lỗi xảy ra. Vui lòng thử lại.',
    NETWORK_ERROR: 'Không kết nối được máy chủ. Kiểm tra kết nối mạng của bạn.',
    INVALID_CREDENTIALS: 'Email hoặc mật khẩu không đúng',
    TOO_MANY_ATTEMPTS: 'Bạn đã nhập sai quá nhiều lần. Vui lòng thử lại sau 15 phút.',
    TOO_MANY_REQUESTS: 'Bạn thao tác quá nhanh. Vui lòng thử lại sau ít phút.',
    EMAIL_TAKEN: 'Email đã được đăng ký. Hãy đăng nhập.',
    INVALID_EMAIL: 'Email không hợp lệ',
    PASSWORD_TOO_SHORT: 'Mật khẩu cần ít nhất 8 ký tự',
    PASSWORD_TOO_LONG: 'Mật khẩu tối đa 128 ký tự',
    WEAK_PASSWORD: 'Mật khẩu quá phổ biến, hãy chọn mật khẩu khác',
    RESET_TOKEN_INVALID: 'Liên kết không hợp lệ hoặc đã hết hạn.',
    INVALID_CHILD_NAME: 'Tên bé cần từ 1 đến 30 ký tự',
    INVALID_BIRTH_DATE: 'Ngày sinh không hợp lệ hoặc ở tương lai',
    CHILD_TOO_OLD: 'Ứng dụng hỗ trợ bé từ 6 đến 24 tháng tuổi',
    INVALID_WEEKS_EARLY: 'Số tuần sinh sớm cần từ 1 đến 16',
    UNKNOWN_INGREDIENT: 'Có nguyên liệu không còn trong danh mục, hãy chọn lại',
    TOO_MANY_AVOID_ITEMS: 'Danh sách thực phẩm cần tránh tối đa 100 nguyên liệu',
    STAGE_ABOVE_AGE: 'Không thể chọn giai đoạn cao hơn tuổi của bé',
    CHILD_NOT_FOUND: 'Không tìm thấy hồ sơ bé',
    MEAL_ALREADY_LOGGED: 'Bữa này đã được ghi nhận, không thể thay đổi nữa.',
    MEAL_CHANGED: 'Bữa này vừa được người nhà đổi sang món khác. Danh sách gợi ý đã được cập nhật.',
    OWNER_ONLY: 'Chỉ chủ hồ sơ được thực hiện thao tác này.',
    ALREADY_MEMBER: 'Bạn đã cùng chăm bé này.',
    MEMBER_LIMIT_REACHED: 'Mỗi bé có tối đa 6 người chăm (gồm chủ hồ sơ).',
    INVITE_LIMIT_REACHED: 'Đã có 5 lời mời đang chờ. Hãy thu hồi bớt lời mời cũ.',
    OWNER_CANNOT_LEAVE: 'Chủ hồ sơ cần chuyển quyền chủ trước khi rời.',
    NOT_A_CAREGIVER: 'Chỉ chuyển quyền chủ cho người đang cùng chăm bé.',
    MEMBER_NOT_FOUND: 'Người này không còn trong hồ sơ bé.',
    INVITE_NOT_FOUND: 'Lời mời không còn.',
    INVALID_DISPLAY_NAME: 'Tên hiển thị tối đa 30 ký tự.',
    OWNERSHIP_TRANSFER_REQUIRED: 'Hãy chuyển quyền chủ các hồ sơ bé còn người chăm trước.',
    MEAL_NOT_FOUND: 'Không tìm thấy bữa ăn này.',
    DISH_NOT_FOUND: 'Không tìm thấy món ăn này.',
    MEAL_IN_PAST: 'Không thể đổi món cho ngày đã qua.',
    SAME_DISH: 'Bữa này đang dùng chính món đó.',
    DISH_NOT_SAFE_FOR_CHILD: 'Món này không còn an toàn cho bé. Danh sách gợi ý đã được cập nhật.',
    DISH_NOT_FOR_SLOT: 'Món này không dùng được cho bữa này.',
    CHILD_NOT_PLANNABLE: 'Bé chưa ở độ tuổi được lập thực đơn (6–24 tháng).',
    MEAL_IN_FUTURE: 'Chưa tới ngày của bữa này.',
    LOGGED_AT_OUT_OF_RANGE: 'Giờ ghi nhận không hợp lý với bữa này.',
    INVALID_LIKING: 'Mức thích cần từ 1 đến 5.',
    REACTION_WITHOUT_SYMPTOM: 'Hãy chọn ít nhất một dấu hiệu bất thường.',
    NOTE_TOO_LONG: 'Ghi chú tối đa 500 ký tự.',
    INGREDIENT_NOT_PAUSED: 'Nguyên liệu này không còn tạm dừng.',
    URGENT_EVENT_NOT_FOUND: 'Không tìm thấy ghi nhận khẩn cấp.',
    INVALID_CURSOR: 'Không tải được trang tiếp theo. Hãy tải lại nhật ký.',
    DISH_NAME_TAKEN: 'Bạn đã có món trùng tên.',
    CUSTOM_DISH_LIMIT_REACHED: 'Mỗi bé có tối đa 50 món tự tạo.',
    INVALID_CUSTOM_DISH: 'Thông tin món chưa hợp lệ.',
    HEALTH_END_BEFORE_START: 'Ngày dự kiến kết thúc phải từ ngày bắt đầu trở đi.',
    HEALTH_START_TOO_FAR: 'Ngày bắt đầu chỉ được trong vòng 7 ngày tới.',
    INVALID_DATE: 'Ngày không hợp lệ.',
    INVALID_WEEK_START: 'Tuần không hợp lệ.',
    WEEK_OUT_OF_RANGE: 'Chỉ lên được thực đơn cho tuần này và tuần kế tiếp.',
    PLAN_EXISTS: 'Tuần này đã có thực đơn.',
  },
} as const;
