/** Every user-facing string lives here (NFR-015). */
export const vi = {
  appName: 'Thực đơn ăn dặm',
  common: {
    retry: 'Thử lại',
    back: 'Quay lại',
    close: 'Đóng',
    loading: 'Đang tải…',
    comingSoon: 'Tính năng đang được xây dựng.',
  },
  nav: {
    label: 'Điều hướng chính',
    today: 'Hôm nay',
    week: 'Tuần',
    dishes: 'Món ăn',
    journal: 'Nhật ký',
    profile: 'Hồ sơ bé',
  },
  health: {
    checking: 'Đang kiểm tra máy chủ…',
    ok: 'Máy chủ hoạt động bình thường',
    down: 'Máy chủ đang gặp sự cố. Vui lòng thử lại sau ít phút.',
    offline: 'Không kết nối được máy chủ. Kiểm tra kết nối mạng của bạn.',
  },
  auth: {
    email: 'Email',
    password: 'Mật khẩu',
    newPassword: 'Mật khẩu mới',
    showPassword: 'Hiện mật khẩu',
    hidePassword: 'Ẩn mật khẩu',
    passwordHint: 'Ít nhất 8 ký tự. Có thể dùng câu dài dễ nhớ.',
    loginTitle: 'Đăng nhập',
    loginSubmit: 'Đăng nhập',
    loginIntro: 'Lên thực đơn ăn dặm an toàn theo độ tuổi của bé.',
    forgotLink: 'Quên mật khẩu?',
    noAccount: 'Chưa có tài khoản?',
    registerLink: 'Tạo tài khoản',
    registerTitle: 'Tạo tài khoản',
    registerSubmit: 'Tạo tài khoản',
    hasAccount: 'Đã có tài khoản?',
    consentLegend: 'Dữ liệu của bé',
    consentSummary:
      'Để lập thực đơn, ứng dụng lưu hồ sơ của bé, bữa ăn và các phản ứng bạn ghi lại. Đây là dữ liệu sức khỏe — dữ liệu cá nhân nhạy cảm — chỉ dùng để lập thực đơn cho bé, không chia sẻ cho bên thứ ba. Bạn có thể xóa toàn bộ dữ liệu bất cứ lúc nào.',
    consentPolicyLink: 'Đọc chính sách đầy đủ',
    consentCheckbox: 'Tôi đồng ý cho ứng dụng xử lý dữ liệu của bé như trên',
    consentRequired: 'Cần đồng ý với chính sách xử lý dữ liệu để tiếp tục',
    consentOutdated: 'Chính sách vừa được cập nhật. Vui lòng tải lại trang và đồng ý lại.',
    forgotTitle: 'Quên mật khẩu',
    forgotIntro: 'Nhập email đã đăng ký, chúng tôi sẽ gửi liên kết đặt lại mật khẩu.',
    forgotSubmit: 'Gửi liên kết',
    forgotSent:
      'Nếu email này đã đăng ký, chúng tôi vừa gửi liên kết đặt lại mật khẩu. Liên kết có hiệu lực trong 30 phút.',
    resetTitle: 'Đặt mật khẩu mới',
    resetSubmit: 'Đặt mật khẩu mới',
    resetDone: 'Đã đổi mật khẩu. Mọi thiết bị khác đã được đăng xuất.',
    resetInvalid: 'Liên kết không hợp lệ hoặc đã hết hạn.',
    resetRequestAgain: 'Gửi liên kết mới',
    backToLogin: 'Đăng nhập',
    signedInAs: 'Đang đăng nhập với',
    logout: 'Đăng xuất',
  },
  privacy: {
    title: 'Chính sách xử lý dữ liệu',
    sections: [
      {
        heading: 'Dữ liệu được thu thập',
        body: 'Email và mật khẩu (đã mã hóa); hồ sơ bé: tên, ngày sinh, thực phẩm cần tránh; bữa ăn, lượng ăn, mức thích, dấu hiệu bất thường và tình trạng sức khỏe bạn ghi lại.',
      },
      {
        heading: 'Mục đích',
        body: 'Chỉ để lập thực đơn phù hợp và an toàn cho bé, và để bạn xem lại nhật ký khi đi khám. Ứng dụng không chẩn đoán bệnh.',
      },
      {
        heading: 'Quyền của bạn',
        body: 'Bạn có thể xem, sửa, và xóa dữ liệu của từng bé hoặc xóa toàn bộ tài khoản. Tài khoản bị xóa sẽ không truy cập được ngay và dữ liệu bị xóa vĩnh viễn trong vòng 30 ngày.',
      },
      {
        heading: 'Bảo mật',
        body: 'Dữ liệu được truyền qua kết nối mã hóa và chỉ tài khoản của bạn truy cập được.',
      },
    ],
  },
  notFound: {
    title: 'Không tìm thấy trang',
    body: 'Trang bạn mở không tồn tại hoặc đã được chuyển đi.',
    home: 'Về trang Hôm nay',
  },
  placeholders: {
    health: 'Tình trạng sức khỏe',
    log: 'Ghi nhận bữa ăn',
    week: 'Thực đơn tuần',
    dishes: 'Món ăn',
    journal: 'Nhật ký',
  },
  onboarding: {
    title: 'Tạo hồ sơ bé',
    next: 'Tiếp tục',
    nameTitle: 'Bé nhà mình tên gì?',
    nameLabel: 'Tên hoặc tên gọi ở nhà của bé',
    nameRequired: 'Nhập tên của bé',
    nameTooLong: 'Tên bé tối đa 30 ký tự',
    birthTitle: (name: string) => `${name} sinh ngày nào?`,
    birthLabel: 'Ngày sinh',
    birthRequired: 'Chọn ngày sinh của bé',
    birthFuture: 'Ngày sinh không thể ở tương lai',
    premature: 'Bé sinh non',
    prematureHint: 'Dùng tuổi hiệu chỉnh theo tư vấn bác sĩ',
    weeksLabel: 'Sinh sớm bao nhiêu tuần?',
    weeksRange: 'Nhập số tuần từ 1 đến 16',
    weeksEarly: (weeks: number) => `Sinh sớm ${weeks} tuần`,
    avoidTitle: (name: string) => `Bé ${name} cần tránh thực phẩm nào?`,
    avoidIntro:
      'Món chứa những thực phẩm này sẽ không bao giờ xuất hiện trong thực đơn — kể cả khi kho món ít.',
    reactionLegend: 'Bé đã từng có phản ứng sau khi ăn?',
    reactions: { never: 'Chưa từng', yes: 'Có — tôi sẽ ghi lại chi tiết', unsure: 'Không chắc' },
    reactionTitle: 'Ghi lại phản ứng trước đây',
    reactionNoteLabel: 'Bé đã phản ứng thế nào, với thực phẩm gì?',
    reactionNotePlaceholder: 'Ví dụ: nổi mẩn ở má khoảng 1 giờ sau khi ăn trứng',
    doctorNote:
      'Nếu bé có vấn đề sức khỏe đặc biệt, hãy trao đổi với bác sĩ trước khi dùng thực đơn gợi ý.',
    summaryTitle: 'Kiểm tra lại thông tin',
    avoidSummary: 'Thực phẩm cần tránh',
    none: 'Không có',
    create: 'Tạo hồ sơ',
    fix: 'Sửa thông tin',
  },
  ageSettings: {
    header: 'Cài đặt độ tuổi',
    title: 'Độ tuổi & giai đoạn ăn dặm',
    intro: 'Thực đơn chọn kết cấu, số bữa và khẩu phần theo giai đoạn này.',
    birthDate: 'Ngày sinh',
    planningAge: 'Tuổi dùng để lên thực đơn',
    updating: 'Đang cập nhật…',
    stages: 'Giai đoạn',
    backToAge: 'Về theo tuổi',
    byAge: 'Theo tuổi',
    unlockAt: (months: number) => `Mở khi bé đủ ${months} tháng`,
    hints: [
      'Nghiền mịn, sệt dần',
      'Nghiền lợn cợn, cháo đặc',
      'Cắt nhỏ, mềm, bé tự cầm',
      'Ăn cùng gia đình, ít gia vị',
    ],
    overrideWarning:
      'Bạn đang giữ giai đoạn sớm hơn tuổi của bé — phù hợp khi bé chưa quen kết cấu mới. Không thể chọn giai đoạn cao hơn tuổi.',
    applied: 'Thực đơn sẽ áp dụng',
    texture: 'Kết cấu',
    portion: 'Khẩu phần mỗi bữa',
    mainMeals: 'Bữa chính / ngày',
    snacks: 'Bữa phụ',
    noSnack: 'Chưa cần',
    tooYoung: 'Dưới 6 tháng, ứng dụng chưa lập thực đơn ăn dặm.',
    tooOld: 'Ứng dụng hỗ trợ bé đến 24 tháng tuổi.',
    save: 'Lưu và cập nhật thực đơn',
    who: 'Tham khảo theo hướng dẫn WHO về ăn bổ sung (6–23 tháng). Dưới 6 tháng, ứng dụng không lập thực đơn ăn dặm.',
  },
  profile: {
    notPlannable: 'Chưa đến tuổi ăn dặm',
    avoidTitle: 'Thực phẩm cần tránh',
    avoidEmpty: 'Chưa có thực phẩm cần tránh',
    editAvoid: 'Sửa thực phẩm cần tránh',
    save: 'Lưu',
    cancel: 'Hủy',
    settings: 'Cài đặt',
    ageLink: 'Độ tuổi & giai đoạn',
    accountLink: 'Tài khoản',
    deleteChild: 'Xóa dữ liệu của bé',
    deleteWarning: (name: string) =>
      `Toàn bộ hồ sơ, thực đơn và nhật ký của ${name} sẽ bị xóa vĩnh viễn và không thể khôi phục.`,
    deleteForever: 'Xóa vĩnh viễn',
  },
  account: {
    title: 'Tài khoản',
    deleteTitle: 'Xóa tài khoản',
    deleteExplain:
      'Tài khoản và dữ liệu của mọi bé sẽ không truy cập được ngay, và bị xóa vĩnh viễn trong vòng 30 ngày.',
    passwordLabel: 'Nhập mật khẩu để xác nhận',
    passwordRequired: 'Nhập mật khẩu hiện tại để xác nhận',
    delete: 'Xóa tài khoản',
  },
  child: {
    newborn: 'Mới sinh',
    corrected: 'hiệu chỉnh',
  },
  allergens: {
    egg: 'Trứng',
    cow_milk: 'Sữa bò',
    peanut: 'Đậu phộng',
    shellfish: 'Tôm, cua',
    fish: 'Cá',
    wheat: 'Lúa mì',
    soy: 'Đậu nành',
    sesame: 'Mè',
    tree_nut: 'Hạt cây',
  },
  avoid: {
    allergensLegend: 'Chất gây dị ứng thường gặp',
    otherLabel: 'Thực phẩm khác bé không ăn hoặc không thích',
    otherPlaceholder: 'Tìm nguyên liệu, ví dụ: cà rốt',
    noResult: 'Không tìm thấy nguyên liệu phù hợp',
    alreadyAdded: (name: string) => `${name} đã có trong danh sách`,
    add: 'Thêm',
    remove: 'Bỏ',
    switchReason: 'Đổi lý do cho',
    reasons: { dislike: 'không thích', not_eat: 'không ăn' },
  },
  slots: {
    breakfast: 'Sáng',
    morning_snack: 'Phụ sáng',
    lunch: 'Trưa',
    afternoon_snack: 'Xế',
    dinner: 'Tối',
    extra_snack: 'Phụ tối',
  },
  foodGroups: {
    carb: 'Tinh bột',
    protein: 'Đạm',
    fat: 'Chất béo',
    veg: 'Rau củ',
    fruit: 'Trái cây',
    seasoning: 'Gia vị',
  },
  proteins: {
    fish: 'Cá',
    chicken: 'Gà',
    beef: 'Bò',
    pork: 'Heo',
    legume: 'Đậu',
    egg: 'Trứng',
  },
  groupsMet: (count: number) => `Đạt ${count}/4 nhóm`,
  minutes: (count: number) => `${count} phút`,
  today: {
    childName: (name: string) => `Bé ${name}`,
    stage: (id: number) => `Giai đoạn ${id}`,
    texture: (label: string) => `Kết cấu: ${label}`,
    health: 'Sức khỏe: Bình thường',
    avoid: (names: string) => `Tránh: ${names}`,
    nextMeal: 'Bữa tiếp theo',
    nextMealAt: (slot: string, time: string) => `Bữa tiếp theo · ${slot} ${time}`,
    due: 'đã tới giờ',
    firstTry: (names: string) => `Lần đầu thử: ${names}.`,
    firstTryAdvice: 'Cho lượng nhỏ và theo dõi bé trong vài giờ sau bữa.',
    prepared: 'Đã chuẩn bị xong',
    preparedDone: 'Đã chuẩn bị xong — cho bé ăn rồi ghi lại nhé.',
    swap: 'Đổi món',
    ate: 'Bé đã ăn',
    reaction: 'Phản ứng',
    listTitle: 'Hôm nay',
    listLabel: 'Thực đơn hôm nay',
    status: {
      next: 'Tiếp theo',
      prepared: 'Đã chuẩn bị',
      eaten: 'Đã ăn',
      refused: 'Bé không ăn',
      skipped: 'Đã bỏ qua',
    },
    snack: 'Bữa phụ',
    unfilled: 'Chưa có món phù hợp',
    unfilledAlert:
      'Chưa tìm được món an toàn cho một số bữa. Thực phẩm bé cần tránh luôn được loại trừ, kể cả khi kho món ít.',
    reviewAvoid: 'Xem thực phẩm cần tránh',
    doneTitle: 'Hôm nay đã xong',
    doneBody: 'Các bữa hôm nay đã được ghi lại. Thực đơn ngày mai sẽ có ở đây từ sáng mai.',
    loading: 'Đang lập thực đơn…',
    tooYoung: 'Dưới 6 tháng, ứng dụng chưa lập thực đơn ăn dặm.',
    tooOld: 'Ứng dụng hỗ trợ bé đến 24 tháng tuổi.',
    checkAge: 'Kiểm tra độ tuổi',
    disclaimer: 'Thực đơn là gợi ý tham khảo, không thay thế tư vấn của nhân viên y tế.',
  },
  recipe: {
    photo: 'Ảnh món ăn',
    reviewed: 'Đã duyệt nội dung',
    notReviewed: 'Chưa được chuyên gia duyệt',
    version: (v: number) => `Công thức v${v}`,
    prep: 'Sơ chế',
    cook: 'Nấu',
    texture: 'Kết cấu',
    tool: 'Dụng cụ',
    byAge: 'Theo độ tuổi',
    byAgeLabel: 'Hướng dẫn theo độ tuổi',
    facts: 'Thông tin món',
    portion: 'Khẩu phần tham khảo',
    ingredients: 'Nguyên liệu · 1 phần',
    ingredientsLabel: 'Nguyên liệu',
    firstTry: '· lần đầu',
    safety: 'Lưu ý an toàn',
    allergens: 'Chứa chất gây dị ứng thường gặp:',
    steps: 'Cách làm',
    swap: 'Đổi món',
    startCooking: 'Bắt đầu nấu',
    excluded: 'Món này hiện không phù hợp với bé',
    exclusions: {
      allergen: 'Món có chất gây dị ứng bé cần tránh.',
      avoid: 'Món có thực phẩm bé không ăn hoặc không thích.',
      paused: 'Món có thực phẩm đang tạm dừng sau một phản ứng.',
      age: 'Món chưa phù hợp với độ tuổi của bé.',
      refused: 'Bé đã từ chối món này gần đây.',
      sick_new: 'Món có thực phẩm mới — chưa nên thử khi bé đang mệt.',
    },
  },
  swap: {
    eyebrow: (slot: string, time: string) => `Bữa ${slot} · ${time}`,
    title: 'Đổi món khác',
    replacing: (name: string) => `Đang thay: ${name}`,
    reasonLegend: 'Vì sao muốn đổi?',
    reasons: {
      missing_ingredient: 'Thiếu nguyên liệu',
      disliked: 'Bé không thích',
      faster: 'Cần nấu nhanh hơn',
      other: 'Lý do khác',
    },
    suggestions: 'Gợi ý thay thế',
    best: 'Phù hợp nhất',
    chooseBest: 'Chọn món này',
    choose: 'Chọn',
    chooseLabel: (name: string) => `Chọn ${name}`,
    updating: 'Đang cập nhật…',
    fasterBy: (minutes: number) => `Nhanh hơn ${minutes} phút`,
    codes: {
      NOT_USED_7D: 'Chưa dùng trong 7 ngày qua',
      LIKED: 'Bé từng ăn hết hoặc rất thích món này',
      FOUR_GROUPS: 'Đủ 4 nhóm chất',
      LEAST_USED_PROTEIN: 'Nguồn đạm bé ít ăn trong tuần',
      NEW_INGREDIENT: 'Có thực phẩm mới để bé làm quen',
    },
    differentProtein: (protein: string, others: string) =>
      `Đạm ${protein} — khác nguồn đạm ${others}`,
    differentProteinAlone: (protein: string) => `Đạm ${protein} — chưa có trong các bữa khác`,
    proteinOther: (slot: string, protein: string) => `bữa ${slot} (${protein})`,
    repeatPast: (days: number) => `Đã dùng ${days} ngày trước`,
    repeatAhead: (days: number) => `Đã có trong thực đơn ${days} ngày tới`,
    relaxed: 'hệ thống nới cửa sổ chống lặp từ 7 xuống 3 ngày vì kho món còn ít.',
    excluded: (count: number, parts: string) => `Đã loại ${count} món: ${parts}.`,
    neverRelaxed: 'Bộ lọc an toàn không bao giờ được nới.',
    noFaster: 'Không có món nào nhanh hơn món hiện tại.',
    none: 'Chưa có món phù hợp để thay.',
    openLibrary: 'Mở thư viện món',
    home: 'Về trang Hôm nay',
  },
  exclusionParts: {
    allergen: (n: string, names: string) => `${n} chứa ${names} (cần tránh)`,
    avoid: (n: string) => `${n} có thực phẩm bé không ăn`,
    paused: (n: string) => `${n} có thực phẩm đang tạm dừng`,
    age: (n: string) => `${n} chưa hợp độ tuổi`,
    refused: (n: string) => `${n} bé từng từ chối`,
    sick_new: (n: string) => `${n} có thực phẩm mới khi bé đang mệt`,
    allergensFallback: 'chất gây dị ứng',
  },
  library: {
    title: 'Món ăn',
    filtered: (name: string, stage: number) => `Đã lọc cho bé ${name} · Giai đoạn ${stage}`,
    avoiding: (names: string) => `tránh ${names}`,
    searchLabel: 'Tìm món',
    searchPlaceholder: 'Tìm món hoặc nguyên liệu',
    chipsLabel: 'Lọc theo nhóm',
    chips: {
      all: 'Tất cả',
      chicken: 'Gà',
      fish: 'Cá',
      beef: 'Bò',
      pork: 'Heo',
      legume: 'Đậu',
      snack: 'Bữa phụ',
    },
    count: (n: number) => `${n} món phù hợp`,
    fresh: 'Chưa ăn 7 ngày',
    main: 'Món chính',
    snack: 'Bữa phụ',
    liked: 'Bé thích',
    firstTry: (names: string) => `Lần đầu: ${names}`,
    eatenToday: {
      breakfast: 'Ăn sáng nay',
      lunch: 'Ăn trưa nay',
      dinner: 'Ăn tối nay',
      other: 'Ăn hôm nay',
    },
    eatenYesterday: 'Ăn hôm qua',
    eatenDaysAgo: (n: number) => `Ăn ${n} ngày trước`,
    empty: 'Chưa có món phù hợp trong nhóm này.',
    emptyQuery: (q: string) => `Không tìm thấy món khớp “${q}”.`,
    dropFresh: 'Bỏ lọc “Chưa ăn 7 ngày”',
    hiddenTitle: (n: number) => `Đang ẩn ${n} món không phù hợp`,
    hiddenMatching: (n: number) => `${n} món khớp từ khóa đang bị ẩn`,
    hiddenLabel: 'Món đang ẩn',
    showHidden: 'Xem các món đang ẩn',
    hideHidden: 'Thu gọn',
    hiddenReasons: {
      allergen: 'có chất gây dị ứng cần tránh',
      avoid: 'có thực phẩm bé không ăn',
      paused: 'có thực phẩm đang tạm dừng',
      age: 'chưa hợp độ tuổi',
      refused: 'bé từng từ chối',
      sick_new: 'có thực phẩm mới khi bé đang mệt',
    },
  },
  textures: {
    puree_smooth: 'Nghiền mịn',
    mashed: 'Nghiền',
    lumpy: 'Lợn cợn',
    minced_soft: 'Cắt nhỏ, mềm',
    family: 'Món gia đình',
  },
  errors: {
    GENERIC: 'Đã có lỗi xảy ra. Vui lòng thử lại.',
    NETWORK_ERROR: 'Không kết nối được máy chủ. Kiểm tra kết nối mạng của bạn.',
    INVALID_CREDENTIALS: 'Email hoặc mật khẩu không đúng',
    TOO_MANY_ATTEMPTS: 'Bạn đã nhập sai quá nhiều lần. Vui lòng thử lại sau 15 phút.',
    TOO_MANY_REQUESTS: 'Bạn thao tác quá nhanh. Vui lòng thử lại sau ít phút.',
    EMAIL_TAKEN: 'Email đã được đăng ký. Hãy đăng nhập.',
    INVALID_EMAIL: 'Email không hợp lệ',
    PASSWORD_TOO_SHORT: 'Mật khẩu cần ít nhất 8 ký tự',
    PASSWORD_TOO_LONG: 'Mật khẩu tối đa 128 ký tự',
    WEAK_PASSWORD: 'Mật khẩu quá phổ biến, hãy chọn mật khẩu khác',
    RESET_TOKEN_INVALID: 'Liên kết không hợp lệ hoặc đã hết hạn.',
    INVALID_CHILD_NAME: 'Tên bé cần từ 1 đến 30 ký tự',
    INVALID_BIRTH_DATE: 'Ngày sinh không hợp lệ hoặc ở tương lai',
    CHILD_TOO_OLD: 'Ứng dụng hỗ trợ bé từ 6 đến 24 tháng tuổi',
    INVALID_WEEKS_EARLY: 'Số tuần sinh sớm cần từ 1 đến 16',
    UNKNOWN_INGREDIENT: 'Có nguyên liệu không còn trong danh mục, hãy chọn lại',
    TOO_MANY_AVOID_ITEMS: 'Danh sách thực phẩm cần tránh tối đa 100 nguyên liệu',
    STAGE_ABOVE_AGE: 'Không thể chọn giai đoạn cao hơn tuổi của bé',
    CHILD_NOT_FOUND: 'Không tìm thấy hồ sơ bé',
    MEAL_ALREADY_LOGGED: 'Bữa này đã được ghi nhận, không thể thay đổi nữa.',
    MEAL_NOT_FOUND: 'Không tìm thấy bữa ăn này.',
    DISH_NOT_FOUND: 'Không tìm thấy món ăn này.',
    MEAL_IN_PAST: 'Không thể đổi món cho ngày đã qua.',
    SAME_DISH: 'Bữa này đang dùng chính món đó.',
    DISH_NOT_SAFE_FOR_CHILD: 'Món này không còn an toàn cho bé. Danh sách gợi ý đã được cập nhật.',
    DISH_NOT_FOR_SLOT: 'Món này không dùng được cho bữa này.',
    CHILD_NOT_PLANNABLE: 'Bé chưa ở độ tuổi được lập thực đơn (6–24 tháng).',
  },
} as const;
